version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongo_image_processor
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: image_processor

volumes:
  mongodb_data:
